# -*- coding: utf-8 -*-
"""中英欄位標籤與報表分組（財報引擎顯示用）。"""

INCOME_GROUPS = [
    {
        "id": "ops",
        "title": "營運表現",
        "keys": [
            "Revenue",
            "OperatingCosts",
            "GrossProfitFromOperations",
            "SellingExpense",
            "AdministrativeExpense",
            "ResearchAndDevelopmentExpense",
            "NetOtherIncomeExpenses",
            "ProfitLossFromOperatingActivities",
        ],
    },
    {
        "id": "below",
        "title": "營業外與稅後",
        "keys": [
            "FinanceCosts",
            "NonoperatingIncomeAndExpenses",
            "ProfitLossBeforeTax",
            "ProfitLoss",
            "ProfitLossAttributableToOwnersOfParent",
            "BasicEarningsLossPerShareTotal",
            "DilutedEarningsLossPerShareTotal",
        ],
    },
    {
        "id": "oci",
        "title": "其他綜合損益",
        "keys": [
            "OCIEquityInstruments",
            "OCINotReclassifiedTotal",
            "OCIReclassifiedTotal",
            "OtherComprehensiveIncomeTotal",
            "ComprehensiveIncome",
        ],
    },
]

BALANCE_GROUPS = [
    {
        "id": "assets",
        "title": "資產",
        "keys": [
            "CashAndCashEquivalents",
            "AccountsReceivableNet",
            "Inventories",
            "CurrentAssets",
            "PropertyPlantAndEquipment",
            "InvestmentAccountedForUsingEquityMethod",
            "IntangibleAssetsAndGoodwill",
            "NoncurrentAssets",
            "Assets",
        ],
    },
    {
        "id": "liab",
        "title": "負債",
        "keys": [
            "ShorttermBorrowings",
            "CurrentLiabilities",
            "LongtermBorrowings",
            "OtherNoncurrentLiabilities",
            "Liabilities",
        ],
    },
    {
        "id": "equity",
        "title": "權益",
        "keys": [
            "OrdinaryShare",
            "EquityAttributableToOwnersOfParent",
            "Equity",
        ],
    },
]

CASHFLOW_GROUPS = [
    {
        "id": "op",
        "title": "營業活動",
        "keys": [
            "ProfitLossBeforeTax",
            "DepreciationExpense",
            "AmortisationExpense",
            "CashFlowsFromUsedInOperations",
            "NetCashFlowsFromUsedInOperatingActivities",
        ],
    },
    {
        "id": "inv",
        "title": "投資活動",
        "keys": [
            "AcquisitionOfPropertyPlantAndEquipment",
            "ProceedsFromDisposalOfPropertyPlantAndEquipment",
            "AcquisitionOfIntangibleAssets",
            "NetCashFlowsFromUsedInInvestingActivities",
        ],
    },
    {
        "id": "fin",
        "title": "籌資活動",
        "keys": [
            "DividendsPaid",
            "NetCashFlowsFromUsedInFinancingActivities",
            "NetIncreaseDecreaseInCashAndCashEquivalents",
            "CashAndCashEquivalentsAtEndOfPeriod",
        ],
    },
]

LABELS_ZH = {
    # Income
    "Revenue": "營業收入",
    "OperatingCosts": "營業成本",
    "GrossProfitFromOperations": "營業毛利",
    "SellingExpense": "推銷費用",
    "AdministrativeExpense": "管理費用",
    "ResearchAndDevelopmentExpense": "研究發展費用",
    "NetOtherIncomeExpenses": "其他收益及費損淨額",
    "ProfitLossFromOperatingActivities": "營業利益",
    "FinanceCosts": "財務成本",
    "NonoperatingIncomeAndExpenses": "營業外收入及支出",
    "ProfitLossBeforeTax": "稅前淨利",
    "ProfitLoss": "本期淨利",
    "ProfitLossAttributableToOwnersOfParent": "歸屬母公司淨利",
    "BasicEarningsLossPerShareTotal": "基本每股盈餘",
    "DilutedEarningsLossPerShareTotal": "稀釋每股盈餘",
    "OCIEquityInstruments": "權益工具未實現損益",
    "OCINotReclassifiedTotal": "不重分類之綜合損益",
    "OCIReclassifiedTotal": "後續可能重分類之綜合損益",
    "OtherComprehensiveIncomeTotal": "其他綜合損益合計",
    "ComprehensiveIncome": "綜合損益總額",
    "RevenueFromInterest": "利息收入",
    "OtherRevenue": "其他收入",
    "ComprehensiveIncomeAttributableToOwnersOfParent": "綜合損益歸屬母公司",
    "ComprehensiveIncomeAttributableToNoncontrollingInterests": "綜合損益歸屬非控制權益",
    "ProfitLossAttributableToNoncontrollingInterests": "歸屬非控制權益淨利",
    "EquityMethodShareOfProfitLoss": "權益法認列之關聯企業及合夥損益",
    "EquityMethodOCINotReclassified": "權益法其他綜合損益－不重分類",
    "ExchangeDifferencesOnTranslation": "國外營運換算差額",
    "EquityMethodOCIReclassified": "權益法其他綜合損益－可能重分類",
    # Cash flow
    "CashAndCashEquivalents": "現金及約當現金",
    "AccountsReceivableNet": "應收帳款淨額",
    "Inventories": "存貨",
    "CurrentAssets": "流動資產",
    "PropertyPlantAndEquipment": "不動產廠房及設備",
    "InvestmentAccountedForUsingEquityMethod": "採用權益法之投資",
    "IntangibleAssetsAndGoodwill": "無形資產及商譽",
    "NoncurrentAssets": "非流動資產",
    "Assets": "資產總計",
    "ShorttermBorrowings": "短期借款",
    "CurrentLiabilities": "流動負債",
    "LongtermBorrowings": "長期借款",
    "OtherNoncurrentLiabilities": "其他非流動負債",
    "Liabilities": "負債總計",
    "OrdinaryShare": "普通股股本",
    "EquityAttributableToOwnersOfParent": "歸屬母公司權益",
    "Equity": "權益總計",
    "EquityAndLiabilities": "權益及負債總計",
    "CurrentFinancialAssetsAtFairValueThroughProfitOrLoss": "透過損益按公允價值衡量之金融資產－流動",
    "CurrentFinancialAssetsAtFairValueThroughOtherComprehensiveIncome": "透過其他綜合損益按公允價值衡量之金融資產－流動",
    "CurrentFinancialAssetsAtAmortisedCost": "按攤銷後成本衡量之金融資產－流動",
    "OtherCurrentFinancialAssets": "其他金融資產－流動",
    "CurrentContractAssets": "合約資產－流動",
    "AccountsReceivableDueFromRelatedPartiesNet": "應收關係人款項淨額",
    "OtherCurrentReceivables": "其他應收款項",
    "CurrentPrepayments": "預付款項",
    "CurrentDeferredTaxAssets": "遞延所得稅資產－流動",
    "NoncurrentAssetsHeldForSaleNet": "待出售非流動資產淨額",
    "OtherCurrentAssets": "其他流動資產",
    "OtherCurrentAssetsOthers": "其他流動資產－其他",
    "NoncurrentFinancialAssetsAtFairValueThroughProfitOrLoss": "透過損益按公允價值衡量之金融資產－非流動",
    "NoncurrentFinancialAssetsAtFairValueThroughOtherComprehensiveIncome": "透過其他綜合損益按公允價值衡量之金融資產－非流動",
    "NoncurrentFinancialAssetsAtAmortisedCost": "按攤銷後成本衡量之金融資產－非流動",
    "NoncurrentContractAssets": "合約資產－非流動",
    "RightofuseAssets": "使用權資產",
    "InvestmentProperty": "投資性不動產",
    "LicencesAndFranchises": "特許權及加盟權",
    "Goodwill": "商譽",
    "OtherIntangibleAssets": "其他無形資產",
    "DeferredTaxAssets": "遞延所得稅資產",
    "OtherNoncurrentAssets": "其他非流動資產",
    "NoncurrentAssetsRecognisedAsIncrementalCostsToObtainContractWithCustomers": "取得客戶合約之增額成本",
    "RecognisedAssetsDefinedBenefitPlan": "確定福利計畫資產",
    "OtherNoncurrentFinancialAssets": "其他金融資產－非流動",
    "OtherNoncurrentAssetsOthers": "其他非流動資產－其他",
    "CurrentCommercialPapersIssuedAndCurrentPortionOfNoncurrentCommercialPapersIssued": "應付短期票券及非流動應付短期票券之流動部分",
    "CurrentContractLiabilities": "合約負債－流動",
    "TradeAndOtherCurrentPayablesToTradeSuppliers": "應付帳款",
    "TradeAndOtherCurrentPayablesToRelatedParties": "應付關係人款項",
    "OtherCurrentPayables": "其他應付款項",
    "OtherPayablesOthers": "其他應付款項－其他",
    "CurrentTaxLiabilities": "當期所得稅負債",
    "CurrentProvisions": "準備－流動",
    "CurrentLeaseLiabilities": "租賃負債－流動",
    "OtherCurrentLiabilities": "其他流動負債",
    "CurrentAdvances": "預收款項",
    "LongtermLiabilitiesCurrentPortion": "長期負債之當期部分",
    "OtherCurrentLiabilitiesOthers": "其他流動負債－其他",
    "NoncurrentFinancialLiabilitiesAtFairValueThroughProfitOrLoss": "透過損益按公允價值衡量之金融負債－非流動",
    "NoncurrentContractLiabilities": "合約負債－非流動",
    "NoncurrentPortionOfNoncurrentBondsIssued": "非流動公司債之非流動部分",
    "NoncurrentProvisions": "準備－非流動",
    "DeferredTaxLiabilities": "遞延所得稅負債",
    "NoncurrentFinanceLeaseLiabilities": "租賃負債－非流動",
    "NoncurrentRecognisedLiabilitiesDefinedBenefitPlan": "確定福利計畫負債",
    "GuaranteeDepositsReceived": "存入保證金",
    "OtherNoncurrentLiabilitiesOthers": "其他非流動負債－其他",
    "CapitalReserve": "資本公積",
    "StatutoryReserve": "法定盈餘公積",
    "SpecialReserve": "特別盈餘公積",
    "UnappropriatedRetainedEarningsAaccumulatedDeficit": "未分配盈餘（累積虧損）",
    "RetainedEarnings": "保留盈餘",
    "OtherEquityInterest": "其他權益",
    "TreasuryShares": "庫藏股票",
    "NoncontrollingInterests": "非控制權益",
    "CurrentFinancialLiabilitiesAtFairValueThroughProfitOrLoss": "透過損益按公允價值衡量之金融負債－流動",
    "IssuedCapital": "已發行股本",
    "DueFromTheCentralBankAndCallLoansToBanks": "存放央行及拆借銀行同業",
    "FinancialAssetsAtFairValueThroughProfitOrLoss": "透過損益按公允價值衡量之金融資產",
    "FinancialAssetsAtFairValueThroughOtherComprehensiveIncome": "透過其他綜合損益按公允價值衡量之金融資產",
    "FinancialAssetsAtAmortisedCost": "按攤銷後成本衡量之金融資產",
    "SecuritiesPurchasedUnderResellAgreements": "附賣回票券及債券投資",
    "ReceivablesNet": "應收款項淨額",
    "LoansDiscountedNet": "貼現及放款淨額",
    "InsuranceContractAndReinsuranceAssetsNet": "保險合約及再保險資產淨額",
    "OtherFinancialAssets": "其他金融資產",
    "DepositsFromBanks": "同業存款",
    "DueToTheCentralBankAndBanks": "央行及同業融資",
    "FinancialLiabilitiesAtFairValueThroughProfitOrLoss": "透過損益按公允價值衡量之金融負債",
    "SecuritiesSoldUnderRepurchaseAgreements": "附買回票券及債券負債",
    "CommercialPapersIssuedNet": "應付商業本票淨額",
    "TradeAndOtherPayables": "應付款項",
    "DepositsFromCustomers": "客戶存款",
    "BondsIssued": "發行債券",
    "OtherBorrowings": "其他借款",
    "Provisions": "準備",
    "OtherFinancialLiabilities": "其他金融負債",
    "InsuranceContractAndReinsuranceContractLiabilities": "保險合約及再保險負債",
    "LeaseLiabilities": "租賃負債",
    "OtherAssets": "其他資產",
    "OtherLiabilities": "其他負債",
    "IntangibleAssets": "無形資產",
    "LeaseLiabilitiesCurrent": "租賃負債－流動",
    "LeaseLiabilitiesNoncurrent": "租賃負債－非流動",
    "OtherEquity": "其他權益",
    "OtherPayables": "其他應付款項",
    # DB 欄位別名（名稱與 catalog 略有不同）
    "TotalCurrentAssets": "流動資產合計",
    "TotalNoncurrentAssets": "非流動資產合計",
    "TotalAssets": "資產總計",
    "TotalCurrentLiabilities": "流動負債合計",
    "TotalNoncurrentLiabilities": "非流動負債合計",
    "TotalLiabilities": "負債總計",
    "TotalEquity": "權益總計",
    "TotalEquityAndLiabilities": "權益及負債總計",
    "TotalLiabilitiesAndEquity": "負債及權益總計",
    "ShortTermBorrowings": "短期借款",
    "LongTermBorrowings": "長期借款",
    "FinancialAssetsCurrentAtFairValueThroughProfitOrLoss": "透過損益按公允價值衡量之金融資產－流動",
    "FinancialAssetsCurrentAtFVOCI": "透過其他綜合損益按公允價值衡量之金融資產－流動",
    "FinancialAssetsNoncurrentAtFVOCI": "透過其他綜合損益按公允價值衡量之金融資產－非流動",
    "FinancialLiabilitiesCurrentAtFairValueThroughProfitOrLoss": "透過損益按公允價值衡量之金融負債－流動",
    "CurrentFinancialAssetsAtFairValueThroughOCI": "透過其他綜合損益按公允價值衡量之金融資產－流動",
    "NoncurrentFinancialAssetsAtFairValueThroughOCI": "透過其他綜合損益按公允價值衡量之金融資產－非流動",
    "NotesReceivableNet": "應收票據淨額",
    "AccountsReceivableRelatedPartiesNet": "應收關係人款項淨額",
    "OtherReceivables": "其他應收款項",
    "CurrentTaxAssets": "當期所得稅資產",
    "InvestmentsAccountedForUsingEquityMethod": "採用權益法之投資",
    "RightOfUseAssets": "使用權資產",
    "ContractLiabilitiesCurrent": "合約負債－流動",
    "NotesPayable": "應付票據",
    "AccountsPayable": "應付帳款",
    "BondsPayable": "應付公司債",
    "ShareCapital": "股本",
    "CapitalSurplus": "資本公積",
    "CapitalStock": "股本",
    "BookValuePerShare": "每股淨值",
    "Prepayments": "預付款項",
    "NoncurrentLiabilities": "非流動負債合計",
    # Income (extended)
    "DepreciationExpense": "折舊費用",
    "AmortisationExpense": "攤銷費用",
    "CashFlowsFromUsedInOperations": "營運產生之現金流量",
    "NetCashFlowsFromUsedInOperatingActivities": "營業活動淨現金流",
    "AcquisitionOfPropertyPlantAndEquipment": "取得不動產廠房設備",
    "ProceedsFromDisposalOfPropertyPlantAndEquipment": "處分不動產廠房設備",
    "AcquisitionOfIntangibleAssets": "取得無形資產",
    "NetCashFlowsFromUsedInInvestingActivities": "投資活動淨現金流",
    "DividendsPaid": "發放現金股利",
    "NetCashFlowsFromUsedInFinancingActivities": "籌資活動淨現金流",
    "NetIncreaseDecreaseInCashAndCashEquivalents": "現金淨增減",
    "CashAndCashEquivalentsAtEndOfPeriod": "期末現金及約當現金",
    "AdjustmentsToReconcileProfitLoss": "調節項目合計",
    "InterestExpense": "利息費用",
    "InterestIncome": "利息收入",
    "InterestReceived": "收取之利息",
    "DividendsReceived": "收取之股利",
    "InterestPaid": "支付之利息",
    "IncomeTaxesPaid": "支付之所得稅",
    "AcquisitionOfInvestments": "取得投資",
    "ProceedsFromDisposalOfInvestments": "處分投資",
    "ProceedsFromIssuingShares": "發行股票",
    "PaymentsToAcquireTreasuryShares": "取得庫藏股票",
    "ProceedsFromBorrowings": "舉借借款",
    "RepaymentsOfBorrowings": "償還借款",
    "PaymentsOfLeaseLiabilities": "償還租賃負債",
    "EffectOfExchangeRateChangesOnCashAndCashEquivalents": "匯率變動對現金之影響",
    "CashAndCashEquivalentsAtBeginningOfPeriod": "期初現金及約當現金",
    "gross_margin": "毛利率",
    "op_margin": "營業利益率",
    "net_margin": "淨利率",
    "roa": "ROA",
    "roe": "ROE",
    "debt_ratio": "負債比率",
    "current_ratio": "流動比率",
    "quick_ratio": "速動比率",
    "cash_ratio": "現金比率",
    "debt_to_equity": "負債權益比",
    "equity_ratio": "權益比率",
    "borrowings_ratio": "借款比率",
    "cash_cl_ratio": "現金對流動負債比",
    "working_capital": "營運資金",
    "operating_cash_flow": "營業活動現金流量",
    "free_cash_flow": "自由現金流量",
    "operating_cash_to_net_income": "營業現金流對淨利比",
    "free_cash_flow_margin": "自由現金流率",
    "roic": "投入資本報酬率（ROIC）",
    "interest_coverage": "利息保障倍數",
    "asset_turnover": "總資產週轉率",
    "inventory_turnover": "存貨週轉率",
    "receivable_turnover": "應收帳款週轉率",
    "payable_turnover": "應付帳款週轉率",
    "inventory_days": "存貨天數",
    "receivable_days": "應收帳款天數",
    "payable_days": "應付帳款天數",
    "cash_conversion_cycle": "現金轉換週期",
    "revenue_yoy": "營收年增率",
    "op_profit_yoy": "營業利益年增率",
    "eps_yoy": "EPS 年增率",
    "revenue_cagr_3y": "營收三年複合成長率",
    "eps_cagr_3y": "EPS 三年複合成長率",
    "book_value_per_share": "每股淨值",
    "free_cash_flow_per_share": "每股自由現金流",
    "dupont_net_margin": "杜邦淨利率",
    "dupont_asset_turnover": "杜邦資產週轉率",
    "dupont_equity_multiplier": "杜邦權益乘數",
}

EMPHASIS_KEYS = {
    "Revenue",
    "GrossProfitFromOperations",
    "ProfitLossFromOperatingActivities",
    "ProfitLoss",
    "BasicEarningsLossPerShareTotal",
    "Assets",
    "TotalAssets",
    "Liabilities",
    "TotalLiabilities",
    "Equity",
    "TotalEquity",
    "CurrentAssets",
    "CurrentLiabilities",
    "NetCashFlowsFromUsedInOperatingActivities",
    "NetCashFlowsFromUsedInInvestingActivities",
    "NetCashFlowsFromUsedInFinancingActivities",
    "CashAndCashEquivalentsAtEndOfPeriod",
}

EPS_KEYS = {
    "BasicEarningsLossPerShareTotal",
    "DilutedEarningsLossPerShareTotal",
}

RATIO_KEYS = [
    "gross_margin",
    "op_margin",
    "net_margin",
    "roa",
    "roe",
    "debt_ratio",
    "equity_ratio",
    "debt_to_equity",
    "borrowings_ratio",
    "current_ratio",
    "quick_ratio",
    "cash_ratio",
    "cash_cl_ratio",
    "operating_cash_flow",
    "free_cash_flow",
    "operating_cash_to_net_income",
    "free_cash_flow_margin",
    "roic",
    "interest_coverage",
    "asset_turnover",
    "inventory_turnover",
    "receivable_turnover",
    "payable_turnover",
    "inventory_days",
    "receivable_days",
    "payable_days",
    "cash_conversion_cycle",
    "revenue_yoy",
    "op_profit_yoy",
    "eps_yoy",
    "revenue_cagr_3y",
    "eps_cagr_3y",
    "book_value_per_share",
    "free_cash_flow_per_share",
    "dupont_net_margin",
    "dupont_asset_turnover",
    "dupont_equity_multiplier",
]

# API 與前端共用的單位契約；percent 值一律使用 DB 小數（0.15 = 15%）。
RATIO_UNITS = {
    **{
        key: "percent"
        for key in (
            "gross_margin",
            "op_margin",
            "net_margin",
            "roa",
            "roe",
            "debt_ratio",
            "equity_ratio",
            "borrowings_ratio",
            "free_cash_flow_margin",
            "roic",
            "revenue_yoy",
            "op_profit_yoy",
            "eps_yoy",
            "revenue_cagr_3y",
            "eps_cagr_3y",
            "dupont_net_margin",
        )
    },
    **{
        key: "multiple"
        for key in (
            "current_ratio",
            "quick_ratio",
            "cash_ratio",
            "cash_cl_ratio",
            "debt_to_equity",
            "operating_cash_to_net_income",
            "interest_coverage",
            "asset_turnover",
            "inventory_turnover",
            "receivable_turnover",
            "payable_turnover",
            "dupont_asset_turnover",
            "dupont_equity_multiplier",
        )
    },
    **{
        key: "days"
        for key in (
            "inventory_days",
            "receivable_days",
            "payable_days",
            "cash_conversion_cycle",
        )
    },
    **{
        key: "currency"
        for key in (
            "operating_cash_flow",
            "free_cash_flow",
            "book_value_per_share",
            "free_cash_flow_per_share",
        )
    },
}

# 以倍數顯示（非百分比），保留給舊版消費端相容。
RATIO_MULTIPLE_KEYS = {
    key for key, unit in RATIO_UNITS.items() if unit == "multiple"
}

# 受損益單季／累計影響，需依換算後損益重算
INCOME_LINKED_RATIO_KEYS = {
    "gross_margin",
    "op_margin",
    "net_margin",
    "roa",
    "roe",
}

FINANCIAL_NOT_APPLICABLE_RATIO_KEYS = {
    "roic",
    "asset_turnover",
    "inventory_turnover",
    "receivable_turnover",
    "payable_turnover",
    "inventory_days",
    "receivable_days",
    "payable_days",
    "cash_conversion_cycle",
    "dupont_asset_turnover",
    "dupont_equity_multiplier",
}

RATIO_SECTIONS = [
    (
        "profit",
        "獲利能力",
        ["gross_margin", "op_margin", "net_margin", "roa", "roe"],
    ),
    (
        "structure",
        "資本結構",
        ["debt_ratio", "equity_ratio", "debt_to_equity", "borrowings_ratio"],
    ),
    (
        "liquidity",
        "流動性",
        ["current_ratio", "quick_ratio", "cash_ratio", "cash_cl_ratio"],
    ),
    (
        "cashflow_quality",
        "現金流品質",
        [
            "operating_cash_flow",
            "free_cash_flow",
            "operating_cash_to_net_income",
            "free_cash_flow_margin",
            "roic",
            "interest_coverage",
        ],
    ),
    (
        "efficiency",
        "營運效率",
        [
            "asset_turnover",
            "inventory_turnover",
            "receivable_turnover",
            "payable_turnover",
            "inventory_days",
            "receivable_days",
            "payable_days",
            "cash_conversion_cycle",
        ],
    ),
    (
        "growth",
        "成長性",
        [
            "revenue_yoy",
            "op_profit_yoy",
            "eps_yoy",
            "revenue_cagr_3y",
            "eps_cagr_3y",
        ],
    ),
    (
        "per_share",
        "每股指標",
        ["book_value_per_share", "free_cash_flow_per_share"],
    ),
    (
        "dupont",
        "杜邦分析",
        [
            "dupont_net_margin",
            "dupont_asset_turnover",
            "dupont_equity_multiplier",
        ],
    ),
]


def groups_for(kind: str):
    if kind == "income":
        return INCOME_GROUPS
    if kind == "balance":
        return BALANCE_GROUPS
    if kind == "cashflow":
        return CASHFLOW_GROUPS
    return []
